clearvars
close all
clc

load FP

V = 5;
L = 20;

%NODES
[NODES,SECTION] = CreateNodes(FP,V,L);

%ELEMENTS
[CQUAD CROD] = ElLong (SECTION,L,V);
CQUAD = [CQUAD ElSkin(SECTION,L,V)];
CQUAD = [CQUAD ElRib(SECTION,L,V)];
CTRIA = ElTria(SECTION,L,V);
CBAR = ElStr(SECTION,NODES,L,V);


%WRITE
writeInp(NODES,SECTION,L,V,CTRIA,CQUAD,CROD,CBAR)
writeBdf(NODES,SECTION,L,V,CTRIA,CQUAD,CROD,CBAR)
%writeBdf(NODES,SECTION,L,V,CBAR)
writeGeom(NODES)